notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /releases\/.+/

language: python
python:
  - 3.6

before_install:
  - export TZ=Asia/Seoul
  - python --version
  - pip install -U pip
  - pip install codecov  

# command to install dependencies
install: pip install -e .[dev]

# command to run tests
script: coverage run --omit="*/test*" -m unittest discover ./tests/ *test.py

after_success:
  - codecov # submit coverage
